"""add public_coolections

Revision ID: 0890d99decfc
Revises: cd1ef4322016
Create Date: 2019-05-08 13:32:11.665798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0890d99decfc'
down_revision = 'cd1ef4322016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_collections', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_collections')
    # ### end Alembic commands ###
