"""add Column can_comment

Revision ID: 0f614fbfe198
Revises: df41f0e9ec36
Create Date: 2019-05-06 13:26:29.564875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f614fbfe198'
down_revision = 'df41f0e9ec36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('can_comment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'can_comment')
    # ### end Alembic commands ###
