"""add locked

Revision ID: 5e4aac553733
Revises: 0890d99decfc
Create Date: 2019-05-09 08:56:49.919079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4aac553733'
down_revision = '0890d99decfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked')
    # ### end Alembic commands ###
