"""1

Revision ID: 5f9ca7621288
Revises: 
Create Date: 2019-05-04 15:46:00.722062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9ca7621288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('filename_m', sa.String(length=64), nullable=True))
    op.add_column('photo', sa.Column('filename_s', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_s')
    op.drop_column('user', 'avatar_m')
    op.drop_column('user', 'avatar_l')
    op.drop_column('photo', 'filename_s')
    op.drop_column('photo', 'filename_m')
    # ### end Alembic commands ###
