"""add Column receive_comment_notification

Revision ID: 9b70ea144ed2
Revises: 0f614fbfe198
Create Date: 2019-05-06 13:55:47.271425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b70ea144ed2'
down_revision = '0f614fbfe198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('receive_comment_notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'receive_comment_notification')
    # ### end Alembic commands ###
