"""add receiver_follow

Revision ID: cd1ef4322016
Revises: 62c36d990143
Create Date: 2019-05-08 13:21:38.268646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1ef4322016'
down_revision = '62c36d990143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('receive_collect_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('receive_follow_notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'receive_follow_notification')
    op.drop_column('user', 'receive_collect_notification')
    # ### end Alembic commands ###
